# Generated by Django 2.2.2 on 2019-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_education_focus_professionalskill_technicalskill_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='achievements',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
