# Generated by Django 2.2.2 on 2019-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20190819_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
