# Generated by Django 2.2.2 on 2019-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20190819_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
