# Generated by Django 2.2.2 on 2019-08-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_projectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contents.ProjectCategory'),
        ),
    ]
