# Generated by Django 2.2.2 on 2019-08-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_project_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contents.ProjectCategory'),
        ),
    ]
