# Generated by Django 2.2.2 on 2019-08-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_auto_20190820_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolsAndTech',
        ),
    ]
