# Generated by Django 2.2.2 on 2019-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_auto_20190820_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsAndTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project', models.ManyToManyField(related_name='toolsandtechs', to='contents.Project')),
            ],
        ),
    ]
