# Generated by Django 2.2.2 on 2019-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_auto_20190820_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='random_col',
            field=models.BooleanField(default=True),
        ),
    ]
