# Generated by Django 2.2.2 on 2019-08-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_project_random_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='random_col',
        ),
    ]
