# Generated by Django 2.2.2 on 2019-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_remove_project_random_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=400)),
                ('summary', models.CharField(max_length=50)),
            ],
        ),
    ]
