# Generated by Django 2.2.2 on 2019-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(default='recommendations/default', upload_to='recommendations'),
        ),
    ]
