# Generated by Django 2.2.2 on 2019-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_recommendation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='achievements',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
