# Generated by Django 2.2.2 on 2019-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0022_auto_20190821_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=30)),
                ('date_issued', models.CharField(max_length=20)),
                ('document', models.FileField(blank=True, upload_to='certifications')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=30)),
                ('event_date', models.CharField(max_length=20)),
                ('document', models.FileField(blank=True, upload_to='seminars')),
            ],
        ),
    ]
