# Generated by Django 2.2.2 on 2019-08-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0023_certification_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='link_proof',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
