# Generated by Django 2.2.2 on 2019-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0024_seminar_link_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='link_icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
