# Generated by Django 2.2.2 on 2020-02-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0026_auto_20200210_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='document',
        ),
        migrations.AddField(
            model_name='certification',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seminar',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(help_text='425x425px recommmended', upload_to='profile_pics'),
        ),
    ]
