# Generated by Django 3.1.2 on 2020-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_auto_20200210_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='link_icon',
        ),
        migrations.AddField(
            model_name='certification',
            name='link_proof',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
