# Generated by Django 3.1.2 on 2020-10-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0028_auto_20201018_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='document_link',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='document_link',
        ),
        migrations.AddField(
            model_name='seminar',
            name='link_icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
