# Generated by Django 3.1.2 on 2020-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0029_auto_20201018_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='link_proof',
        ),
        migrations.AddField(
            model_name='certification',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seminar',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
